# .github/workflows/dotnet-windows-build.yml
name: Build .NET Framework Windows Forms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install NuGet dependencies
        run: nuget restore WindowsFormsApp/WindowsFormsApp/WindowsFormsApp.csproj

      - name: Locate MSBuild
        id: locate-msbuild
        run: |
          $msbuildPath = (vswhere -latest -products * -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe')
          "msbuildPath=$msbuildPath" | Out-File -Append -FilePath $env:GITHUB_OUTPUT

      - name: Build solution
        run: |
          $msbuild = "${{ steps.locate-msbuild.outputs.msbuildPath }}"
          & "$msbuild" 'WindowsFormsApp/WindowsFormsApp/WindowsFormsApp.csproj' /p:Configuration=Release

      - name: Locate VSTest
        id: locate-vstest
        run: |
            $vstestpath = (vswhere -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -find Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe)
            "vstestpath=$vstestpath" | Out-File -Append -FilePath $env:GITHUB_OUTPUT

      - name: Run tests
        run: |
          $vstest = '${{ steps.locate-vstest.outputs.vstestpath }}'
          & "$vstest" **/*.Tests.dll --logger:trx
        continue-on-error: true

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsFormsApp
          path: '**/bin/Release/*.nupkg'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: WindowsFormsApp

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push **/*.nupkg --source "github" --api-key ${{ secrets.TOKEN_GENERIC }}
        env:
          TOKEN_GENERIC: ${{ secrets.TOKEN_GENERIC }}      