# .github/workflows/dotnet-windows-build.yml
name: Build .NET Framework Windows Forms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8'

      - name: Install NuGet dependencies
        run: nuget restore

      - name: Build solution
        run: msbuild WindowsFormsApp/WindowsFormsApp.sln /p:Configuration=Release

      - name: Run tests
        run: |
          vstest.console.exe **/*.Tests.dll --logger:trx
        continue-on-error: true

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsFormsApp
          path: '**/bin/Release/*'

